Repository domaindrivendev/Swashbuckle.AspNetCore, pull requests merged in 2024-09, with the labels that each got.

#3050 Add benchmarks project
  .gitignore
  Directory.Packages.props
  Swashbuckle.AspNetCore.sln
  benchmark.ps1
  perf/Swashbuckle.AspNetCore.Benchmarks/Program.cs
  perf/Swashbuckle.AspNetCore.Benchmarks/Swashbuckle.AspNetCore.Benchmarks.csproj
  perf/Swashbuckle.AspNetCore.Benchmarks/XmlCommentsBenchmark.cs
Labels: dependencies, .NET

#3064 Fix NuGet badge
  README.md
Labels: bug fix, documentation

#3085 Fixing breaking change when applying filters for WithOpenApi extension
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
  test/WebSites/Basic/Controllers/FilesController.cs
  test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
Labels: bug fix
