Repository domaindrivendev/Swashbuckle.AspNetCore, pull requests merged in 2024-11, with the labels that each got.

#3134 Apply SwaggerIgnore on Newtonsoft
  src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/Swashbuckle.AspNetCore.Newtonsoft.Test.csproj
Labels: bug fix

#3133 Fix FromForm without WithOpenApi schemas
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_6.verified.txt
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_8.verified.txt
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_For_WebApi_swaggerRequestUri=v1.verified.txt
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.TypesAreRenderedCorrectly.verified.txt
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_Works_As_Expected_When_FromFormObject.verified.txt
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.GetSwagger_Works_As_Expected_When_FromFormObject_AndString.verified.txt
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.cs
  test/WebSites/Basic/Controllers/FromFormParamsController.cs
  test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs
  test/WebSites/WebApi/EndPoints/SwaggerAnnotationsEndpoints.cs
Labels: bug fix, version-major

#3143 Update some nugets
  Directory.Packages.props
Labels: dependencies, .NET

#3146 Recreate package lock files
  src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
  src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
Labels: dependencies, javascript

#3164 Fix issue with FromForm and enums for Controllers
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_Basic_DotNet_8.verified.txt
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerVerifyIntegrationTest.SwaggerEndpoint_ReturnsValidSwaggerJson_startupType=Basic.Startup_swaggerRequestUri=v1.verified.txt
Labels: bug fix

#3119 Avoid exception checking nullability
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/MemberInfoExtensionsTests.cs
Labels: bug fix

#3171 Fix NotSupportedException in AoT test project
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
Labels: bug fix

#3168 Create snupkg files
  Directory.Build.props
Labels: bug fix

#3175 Update Microsoft.NET.Test.Sdk
  Directory.Packages.props
Labels: dependencies, .NET

#3178 Add package README
  src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.nuspec
Labels: bug fix
