Repository domaindrivendev/Swashbuckle.AspNetCore, pull requests merged in 2024-04, with the labels that each got.

#2768 Grammatical correction of some comments
  src/Swashbuckle.AspNetCore.Annotations/AnnotationsOperationFilter.cs
  src/Swashbuckle.AspNetCore.Annotations/AnnotationsSchemaFilter.cs
Labels: documentation

#2746 Update README.md for nested types custom schemaId support
  README.md
Labels: documentation

#2414 Add support for `WithSummary` and `WithDescription` metadata
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Swashbuckle.AspNetCore.SwaggerGen.Test.csproj
Labels: bug fix

#2705 Update README.md - Fix `Add Security Definitions and Requirements for Bearer auth` URL
  README.md
Labels: bug fix, documentation

#2392 Replace <see href="link">text</see> with Markdown link format
  src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsTextHelperTests.cs
Labels: feature suggestion

#2810 Add support for required keyword
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
  test/Swashbuckle.AspNetCore.TestSupport/ApiExplorer/ApiDescriptionFactory.cs
Labels: feature suggestion

#2610 Added Swashbuckle.AspNetCore.Annotations.SwaggerIgnoreAttribute
  src/Swashbuckle.AspNetCore.SwaggerGen/Annotations/SwaggerIgnoreAttribute.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/SwaggerIngoreAnnotatedType.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Labels: feature suggestion

#2784 Handle Stream and PipeReader content types correctly
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Labels: bug fix

#2808 Add NuGet package READMEs
  Directory.Build.props
  README.md
  package-readme.md
Labels: documentation

#2807 Bump redoc to 2.1.3
  .github/dependabot.yml
  src/Swashbuckle.AspNetCore.ReDoc/package-lock.json
  src/Swashbuckle.AspNetCore.ReDoc/package.json
Labels: dependencies, javascript

#2797 Throw if unsupported HTTP method used
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Labels: bug fix

#2796 Fix configuration properties not being copied
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenServiceCollectionExtensions.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSchemaGeneratorOptionsTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/ConfigureSwaggerGeneratorOptionsTests.cs
Labels: bug fix

#2806 Update to Swagger UI v5
  .github/dependabot.yml
  src/Swashbuckle.AspNetCore.SwaggerUI/package-lock.json
  src/Swashbuckle.AspNetCore.SwaggerUI/package.json
Labels: dependencies, javascript

#2677 Add customized document serialization support
  Swashbuckle.AspNetCore.sln
  src/Swashbuckle.AspNetCore.Cli/Program.cs
  src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerOptionsExtensions.cs
  src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerServiceCollectionExtensions.cs
  src/Swashbuckle.AspNetCore.Swagger/ISwaggerDocumentSerializer.cs
  src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
  src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/DocumentProvider.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptions.cs
  test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
  test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/CustomDocumentSerializerTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
  test/Swashbuckle.AspNetCore.TestSupport/Utilities/TemporaryDirectory.cs
  test/WebSites/CustomDocumentSerializer/Controllers/WeatherForecastController.cs
  test/WebSites/CustomDocumentSerializer/CustomDocumentSerializer.csproj
  test/WebSites/CustomDocumentSerializer/DocumentSerializerTest.cs
  test/WebSites/CustomDocumentSerializer/Program.cs
  test/WebSites/CustomDocumentSerializer/Properties/launchSettings.json
  test/WebSites/CustomDocumentSerializer/Startup.cs
  test/WebSites/CustomDocumentSerializer/WeatherForecast.cs
  test/WebSites/CustomDocumentSerializer/appsettings.Development.json
  test/WebSites/CustomDocumentSerializer/appsettings.json
  test/WebSites/NswagClientExample/swagger.json
Labels: feature suggestion

#2837 Added documentation for ISwaggerDocumentSerializer
  README.md
Labels: documentation

#2842 Filter illegal header fields
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/FakeController.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
  test/WebSites/Basic/Controllers/FromHeaderParamsController.cs
Labels: bug fix
