Repository domaindrivendev/Swashbuckle.AspNetCore, pull requests merged in 2024-05, with the labels that each got.

#2850 Fix RequestBodyFilters not being deep copied
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs
Labels: bug fix

#2848 Avoid GitHub step summary file write conflicts
  Directory.Build.targets
  test/Swashbuckle.AspNetCore.IntegrationTests/CustomDocumentSerializerTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/DocumentProviderTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
Labels: bug fix

#2804 Extend built-in supported types
  src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Labels: feature suggestion

#2856 Update compatibility table
  README.md
Labels: documentation

#2788 Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/ISSUE_TEMPLATE/20_feature_request.yml
  .github/ISSUE_TEMPLATE/30_question.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: documentation

#2855 Fix stale permissions
  .github/workflows/stale.yml
Labels: github_actions

#2809 Release automation workflows
  .github/workflows/bump-version.yml
  .github/workflows/release.yml
Labels: github_actions

#2800 Support native AoT with SwaggerUI
  Swashbuckle.AspNetCore.sln
  src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/JavascriptStringEnumConverter.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/JavascriptStringEnumEnumerableConverter.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIJsonSerializerContext.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
  test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
  test/WebSites/WebApi.Aot/Program.cs
  test/WebSites/WebApi.Aot/Properties/launchSettings.json
  test/WebSites/WebApi.Aot/WebApi.Aot.csproj
  test/WebSites/WebApi.Aot/WebApi.Aot.http
  test/WebSites/WebApi.Aot/appsettings.Development.json
  test/WebSites/WebApi.Aot/appsettings.json
Labels: aot, bug fix

#2863 Fix stale permissions
  .github/workflows/stale.yml
Labels: github_actions

#2872 Add descriptions for more HTTP status codes
  README.md
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
  test/WebSites/CliExample/wwwroot/swagger/v1/swagger.json
  test/WebSites/CliExampleWithFactory/wwwroot/swagger/v1/swagger.json
  test/WebSites/NswagClientExample/swagger.json
Labels: feature suggestion

#2879 Fix to make required and nullable properties nullable in schema
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
Labels: bug fix

#2883 Update Swagger UI section in README
  README.md
Labels: documentation

#2882 Add support for the `[Length]`attribute.
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/OpenApiSchemaExtensions.cs
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributes.cs
  test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithValidationAttributesViaMetadataType.cs
Labels: feature suggestion

#2886 Existing output file should be deleted/overwritten
  src/Swashbuckle.AspNetCore.Cli/Program.cs
  test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
Labels: bug fix

#2897 Avoid competing swagger generation during test build
  test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
  test/WebSites/CliExample/CliExample.csproj
  test/WebSites/CliExample/wwwroot/swagger/v1/swagger_net6.0.json
  test/WebSites/CliExample/wwwroot/swagger/v1/swagger_net7.0.json
  test/WebSites/CliExample/wwwroot/swagger/v1/swagger_net8.0.json
  test/WebSites/CliExampleWithFactory/CliExampleWithFactory.csproj
  test/WebSites/CliExampleWithFactory/wwwroot/swagger/v1/swagger_net6.0.json
  test/WebSites/CliExampleWithFactory/wwwroot/swagger/v1/swagger_net7.0.json
  test/WebSites/CliExampleWithFactory/wwwroot/swagger/v1/swagger_net8.0.json
  test/WebSites/NswagClientExample/NswagClientExample.csproj
  test/WebSites/NswagClientExample/swagger_net6.0.json
  test/WebSites/NswagClientExample/swagger_net8.0.json
Labels: bug fix

#2901 Fix schema generation for c#9 positional record with param tag without example property creating unexpected empty example
  src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedRecord.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedRecordWithoutExample.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedType.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/XmlAnnotatedTypeWithoutExample.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsSchemaFilterTests.cs
Labels: bug fix

#2880 Do not run IHostedService implementations
  Swashbuckle.AspNetCore.sln
  src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs
  src/Swashbuckle.AspNetCore.Cli/HostFactoryResolver.cs
  src/Swashbuckle.AspNetCore.Cli/HostingApplication.cs
  test/Swashbuckle.AspNetCore.Cli.Test/CommandRunnerTests.cs
  test/Swashbuckle.AspNetCore.Cli.Test/Swashbuckle.AspNetCore.Cli.Test.csproj
  test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
  test/WebSites/MinimalAppWithHostedServices/MinimalAppWithHostedServices.csproj
  test/WebSites/MinimalAppWithHostedServices/Program.cs
  test/WebSites/MinimalAppWithHostedServices/Properties/launchSettings.json
Labels: bug fix

#2907 Fix interceptor JSON casing
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
Labels: bug fix

#2895 Fix generation when [DefaultValue]'s type differs
  Swashbuckle.AspNetCore.sln
  src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs
  src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/Swashbuckle.AspNetCore.IntegrationTests.csproj
  test/Swashbuckle.AspNetCore.Newtonsoft.Test/SchemaGenerator/NewtonsoftSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs
  test/Swashbuckle.AspNetCore.TestSupport/Fixtures/TypeWithDefaultAttributes.cs
  test/WebSites/MvcWithNullable/MvcWithNullable.csproj
  test/WebSites/MvcWithNullable/Program.cs
  test/WebSites/MvcWithNullable/Properties/launchSettings.json
  test/WebSites/MvcWithNullable/appsettings.Development.json
  test/WebSites/MvcWithNullable/appsettings.json
  test/WebSites/WebApi/Program.cs
Labels: bug fix
