Repository domaindrivendev/Swashbuckle.AspNetCore, pull requests merged in 2025-03, with the labels that each got.

#3309 Fix DescribeAllParametersInCamelCase usage in GenerateOpenApiOperationFromMetadataAsync
  src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs
  test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGenerator/SwaggerGeneratorTests.cs
Labels: bug fix

#3294 More reliable coverage
  Directory.Build.targets
Labels: bug fix

#3286 Deprecate SerializeAsV2
  README.md
  src/Swashbuckle.AspNetCore.Cli/Program.cs
  src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net6.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net8.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net9.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net9.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/SwaggerEndpointOptions.cs
  src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs
  src/Swashbuckle.AspNetCore.Swagger/SwaggerOptions.cs
  src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
  src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/DocumentProvider.cs
  test/Swashbuckle.AspNetCore.Cli.Test/ToolTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/CustomDocumentSerializerTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs
  test/WebSites/Basic/Startup.cs
  test/WebSites/CustomDocumentSerializer/Startup.cs
  test/WebSites/ReDoc/Startup.cs
Labels: version-major

#3317 Improve release automation
  .github/bump-version.ps1
  .github/update-baselines.ps1
  .github/workflows/bump-version.yml
  Swashbuckle.AspNetCore.sln
  src/Swashbuckle.AspNetCore.Annotations/PublicAPI/net6.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Annotations/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net6.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.Swagger/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/net6.0/PublicAPI.Shipped.txt
  src/Swashbuckle.AspNetCore.SwaggerGen/PublicAPI/net6.0/PublicAPI.Unshipped.txt
Labels: github_actions

#3323 Update version table
  README.md
Labels: documentation

#3341 Add cache headers for ReDoc and SwaggerUI
  Directory.Build.props
  src/Swashbuckle.AspNetCore.Cli/Program.cs
  src/Swashbuckle.AspNetCore.ReDoc/PublicAPI/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs
  src/Swashbuckle.AspNetCore.ReDoc/ReDocOptions.cs
  src/Swashbuckle.AspNetCore.ReDoc/ResourceHelper.cs
  src/Swashbuckle.AspNetCore.ReDoc/Swashbuckle.AspNetCore.ReDoc.csproj
  src/Swashbuckle.AspNetCore.SwaggerUI/PublicAPI/PublicAPI.Unshipped.txt
  src/Swashbuckle.AspNetCore.SwaggerUI/ResourceHelper.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs
  src/Swashbuckle.AspNetCore.SwaggerUI/Swashbuckle.AspNetCore.SwaggerUI.csproj
  test/Swashbuckle.AspNetCore.IntegrationTests/ReDocIntegrationTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerUIIntegrationTests.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/TestSite.cs
  test/Swashbuckle.AspNetCore.IntegrationTests/TestSiteAutofaq.cs
Labels: version-minor
